from orchestrator import CortexOrchestrator

print('=== Cortex Architecture Demo ===')
print()

o = CortexOrchestrator(use_llm=False)
o.initialize()
o.load_workflow('task_approval', '../workflows/task_approval.yaml')

wf_id = 'task_approval'

print('--- Step 1: Create Task ---')
r1 = o.orchestrate('Creer une nouvelle tache', workflow_id=wf_id)
print(f'Message: Creer une nouvelle tache')
print(f'Intent: {r1.intent} | Action: {r1.action_taken}')
print(f'Success: {r1.success} | State: {r1.new_state.get("active_places") if r1.new_state else "N/A"}')
print()

print('--- Step 2: Submit for Approval (Petri Net transition) ---')
instance_id = r1.workflow_instance_id
result = o.workflow_engine.fire_by_action(instance_id, 'submit')
state = o.workflow_engine.get_state(instance_id)
print(f'Fired: submit | New state: {state.get("active_places")}')
print()

print('--- Step 3: Approve (same instance) ---')
o.workflow_engine.fire_by_action(instance_id, 'approve')
state = o.workflow_engine.get_state(instance_id)
print(f'Fired: approve | New state: {state.get("active_places")}')
print(f'Is Complete: {state.get("is_complete")}')
print()

print('--- Step 4: Reject (separate workflow) ---')
r4 = o.orchestrate('Rejeter cette demande', workflow_id=wf_id)
print(f'Message: Rejeter cette demande')
print(f'Intent: {r4.intent} | Action: {r4.action_taken}')
print(f'Success: {r4.success}')
print(f'State: {r4.new_state.get("active_places") if r4.new_state else "N/A"}')
print()

print('========================================')
print('ARCHITECTURE: Neuro-Symbolic Hybrid')
print('========================================')
print()
print('1. SEMANTIC LAYER (Gemma4/Mock)')
print('   - Input: "Creer une tache"')
print('   - Output: {intent: CREATE, topics: [task]}')
print('   - LLM called: 1')
print()
print('2. RULE ENGINE')
print('   - IF intent=CREATE AND topic=task')
print('   - THEN fire_transition("create")')
print('   - LLM called: 0')
print()
print('3. PETRI NET (Formal Coordination)')
print('   - Places: created -> pending_review -> approved')
print('   - Transitions verified: no LLM calls')
print('   - Deadlock detection: enabled')
print()
print('RESULT: 1 LLM call for coordination')
print('(vs LangGraph: every step requires LLM)')
